mobiles = [
    {
        "name": "a52s5g",
        "brand": "samsung",
        "nw": "5g",
        "price": 37000,
        "image": "https://m.media-amazon.com/images/I/81-nNnxa6VS._SX679_.jpg",
    },
    {
        "name": "oppo35",
        "brand": "samsung",
        "nw": "5g",
        "price": 37000,
        "image": "https://m.media-amazon.com/images/I/81-nNnxa6VS._SX679_.jpg",
    },
    {
        "name": "realmegt",
        "brand": "rekme",
        "nw": "5g",
        "price": 37000,
        "image": "https://m.media-amazon.com/s/I/81-nNnxa6VS._SX679_.jpg",
    },
    {
        "name": "vivo",
        "brand": "relme",
        "nw": "5g",
        "price": 37000,
        "image": "https://m.media-amazon.com/s/I/81-nNnxa6VS._SX679_.jpg",
    },
    {
        "name": "iq7",
        "brand": "iq",
        "nw": "5g",
        "price": 24000,
        "image": "https://m.media-amazon.com/s/I/81-nNnxa6VS._SX679_.jpg",
    },
    {
        "name": "samsungf32",
        "brand": "samsung",
        "nw": "5g",
        "price": 37000,
        "image": "https://m.media-amazon.com//I/81-nNnxa6VS._SX679_.jpg",
    },
    {
        "name": "samsunfe",
        "brand": "samsung",
        "nw": "5g",
        "price": 37000,
        "image": "https://m.media-amazon.com/s/I/81-nNnxa6VS._SX679_.jpg",
    },
    {
        "name": "mi11i",
        "brand": "samsung",
        "nw": "5g",
        "price": 37000,
        "image": "https://m.media-amazon.com/s/I/81-nNnxa6VS._SX679_.jpg",
    },
    {
        "name": "mi10pro",
        "brand": "samsung",
        "nw": "5g",
        "price": 22000,
        "image": "https://m.media-amazon.com/s/I/81-nNnxa6VS._SX679_.jpg",
    },
    {
        "name": "mi10promax",
        "brand": "samsung",
        "nw": "5g",
        "price": 47000,
        "image": "https://m.media-amazon.com//I/81-nNnxa6VS._SX679_.jpg",
    },
]